const fs=require('fs'),vm=require('vm'),crypto=require('crypto').webcrypto;
const ROOT=__dirname+'/..';
function element(){return {innerHTML:'',dataset:{},textContent:'',style:{setProperty:()=>{}},classList:{add:()=>{},remove:()=>{},toggle:()=>{}},querySelector:()=>null,querySelectorAll:()=>[],addEventListener:()=>{},remove:()=>{},scrollIntoView:()=>{}}}
function seed(pet={}){return {version:6,onboardingDone:true,onboardingIntroCompleted:true,onboardingStep:6,ageGroup:'7-11',difficultyMode:'easy',pet:{type:'cat',name:'Финни',color:'#7C8CF8',accessory:'none',satiety:70,mood:70,energy:80,care:66,development:10,...pet},wallet:{balance:1000,savings:300,weeklyIncome:1000,week:3,day:2,nextIncomeIn:6,needsSpent:0},activeGoal:null,goalContributions:0,goalAdjustments:{},completedGoals:[],inventory:[],completedTasks:[],achievements:[],transactions:[],financialHealth:68,xp:0,streak:1,stats:{needsFirst:0,positiveDecisions:0,budgetViews:0,tasksDone:0,impulsePurchases:0,reserveUsed:0,petNeedsIgnored:0,weeksBalanced:0},currentEventId:'e42',currentChainId:null,eventResolved:false,recentEventIds:[],weekNeedsPlanning:false,weekPlan:{week:3,necessary:400,wants:200,savings:200,reserve:200},initialWeekPlan:{week:3,necessary:400,wants:200,savings:200,reserve:200},weekSnapshot:{week:3,startingBalance:1000,startingSavings:300,pet:{mood:70,health:66,development:10},worldStage:2,inventoryIds:[],areas:['home']},weekSummary:null,weekHistory:[{week:1},{week:2}],weekOpeningCharges:[],weekOpeningBalance:1000,clubs:{unlocked:true,unlockedWeek:3,activeId:null,joinedWeek:null,currentWeekDecision:null,choiceSkippedWeek:3,pendingId:null,pendingStop:false,skippedWeeks:[],history:[],progress:{}},emergencyCare:{week:3,food:0,mood:0,health:0,history:[]},dayActions:{count:0,necessary:0,optional:0,income:0,sideJob:false},petWish:null,analytics:[],futureObligations:[],worldProgress:{stage:2,areas:['home'],unlocks:[],decor:[]},worldPlacements:{},currentWorldArea:'home',storyChains:{},activityLimits:{week:3,sideJobs:0},workState:{week:3,shiftsUsed:0,shiftsLimit:3,activityUsage:{}},workSession:null,settings:{sound:true,motion:true}}}
function boot(s){const app=element(),store={finpet_mvp_state_v1:JSON.stringify(s)};const localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]};const document={documentElement:{dataset:{}},getElementById:id=>id==='app'?app:null,querySelector:()=>null,querySelectorAll:()=>[],createElement:element,body:{appendChild:()=>{}},addEventListener:()=>{}};const sb={window:null,document,localStorage,location:{protocol:'file:'},navigator:{},crypto,Intl,console,confirm:()=>true,Math,matchMedia:()=>({matches:false}),setTimeout:(fn,ms)=>{if(ms<=1000)fn();return 1},clearTimeout:()=>{}};sb.window=sb;sb.window.scrollTo=()=>{};vm.createContext(sb);vm.runInContext(fs.readFileSync(ROOT+'/content.js','utf8'),sb);vm.runInContext(fs.readFileSync(ROOT+'/app.js','utf8'),sb);return {dev:sb.FINPET_DEV,app}}
function assert(v,m){if(!v)throw new Error(m)}
let r=boot(seed()),d=r.dev,s=d.getState();
assert(s.pet.health===66,'legacy care did not migrate to health');assert(s.pet.care===66,'legacy mirror broken');
let home=d.setRoute('home');assert(home.includes('Здоровье')&&!home.includes('>Уход<'),'care label still visible');
d.actions.setShopCategory('Здоровье');let shop=d.setRoute('shop');assert(shop.includes('Гигиенические принадлежности')&&shop.includes('Домашний спа-день'),'health shop missing');
const C=d.getContent();assert(C.items.find(x=>x.id==='food_basic').effect.health===5,'healthy food health effect missing');assert(C.items.find(x=>x.id==='food_snack').name==='Бургер'&&C.items.find(x=>x.id==='food_treat').name==='Мороженое','food choices missing');
const h0=d.getState().pet.health;d.actions.quickAction('care');assert(d.getState().pet.health>h0,'health action failed');
r=boot(seed({health:0,care:0}));d=r.dev;assert(d.actions.advanceDay()===false,'health zero did not block');assert(d.critical.emergency('health')===true&&d.getState().pet.health===15,'free health help failed');
r=boot(seed({health:29,care:29}));d=r.dev;home=d.setRoute('home');assert(home.includes('Стоит позаботиться о здоровье'),'low health warning missing');
r=boot(seed());d=r.dev;const b=d.getState().wallet.balance;d.actions.openEvent('e42');d.actions.resolveEvent(0);assert(d.getState().wallet.balance===b-60,'friend cinema charge wrong');assert(d.actualsForWeek().wants>=60,'friend cinema not in wants');
r=boot(seed({health:70,care:70}));d=r.dev;d.actions.openEvent('e41');assert(d.getState().healthCondition==='cold'&&d.getState().pet.health===58,'cold open effect missing');d.actions.resolveEvent(0);assert(d.getState().healthCondition===null&&d.getState().pet.health>58,'cold treatment failed');
const src=fs.readFileSync(ROOT+'/app.js','utf8'),css=fs.readFileSync(ROOT+'/styles.css','utf8');assert(src.includes('const migratedHealth='),'migration missing');assert(css.includes('V19 PET HEALTH'),'styles missing');
console.log('health_system_smoke: OK');