const fs=require('fs'),vm=require('vm'),crypto=require('crypto').webcrypto,path=require('path');
const ROOT=__dirname+'/..';
function element(){return {innerHTML:'',dataset:{},style:{setProperty:()=>{}},classList:{add:()=>{},remove:()=>{},toggle:()=>{}},querySelector:()=>null,querySelectorAll:()=>[],addEventListener:()=>{},remove:()=>{},scrollIntoView:()=>{}}}
function seed(){return {version:6,onboardingDone:true,onboardingIntroCompleted:true,onboardingStep:6,ageMigrationPending:false,helpLastTopic:null,ageGroup:'7-11',difficultyMode:'easy',pet:{type:'cat',name:'Финни',color:'#7C8CF8',accessory:'none',satiety:60,mood:70,energy:80,health:70,development:10},wallet:{balance:1000,savings:0,weeklyIncome:1000,week:3,day:2,nextIncomeIn:6,needsSpent:0},activeGoal:null,goalContributions:0,goalAdjustments:{},completedGoals:[],inventory:[],completedTasks:[],achievements:[],transactions:[],financialHealth:68,xp:0,streak:1,stats:{needsFirst:0,positiveDecisions:0,budgetViews:0,tasksDone:0,impulsePurchases:0,reserveUsed:0,petNeedsIgnored:0,weeksBalanced:0},currentEventId:'e12',currentChainId:null,eventResolved:true,recentEventIds:[],weekNeedsPlanning:false,weekPlan:{week:3,necessary:400,wants:200,savings:200,reserve:200},initialWeekPlan:{week:3,necessary:400,wants:200,savings:200,reserve:200},weekSnapshot:{week:3,startingBalance:1000,startingSavings:0,pet:{mood:70,health:70,development:10},worldStage:2,inventoryIds:[],areas:['home']},weekSummary:null,weekHistory:[{week:1},{week:2}],weekOpeningCharges:[],weekOpeningBalance:1000,clubs:{unlocked:true,unlockedWeek:3,activeId:null,joinedWeek:null,currentWeekDecision:null,choiceSkippedWeek:3,pendingId:null,pendingStop:false,skippedWeeks:[],history:[],progress:{}},emergencyCare:{week:3,food:0,mood:0,health:0,history:[]},dayActions:{count:0,necessary:0,optional:0,income:0,sideJob:false},petWish:null,analytics:[],futureObligations:[],worldProgress:{stage:2,areas:['home'],unlocks:[],decor:[]},worldPlacements:{},currentWorldArea:'home',storyChains:{},activityLimits:{week:3,sideJobs:0},workState:{week:3,shiftsUsed:0,shiftsLimit:3,activityUsage:{}},workSession:null,settings:{sound:true,motion:true}}}
function boot(){const app=element(),store={finpet_mvp_state_v1:JSON.stringify(seed())};const localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]};const document={documentElement:{dataset:{}},getElementById:id=>id==='app'?app:null,querySelector:()=>null,querySelectorAll:()=>[],createElement:element,body:{appendChild:()=>{}},addEventListener:()=>{}};const sb={window:null,document,localStorage,location:{protocol:'file:'},navigator:{},crypto,Intl,console,confirm:()=>true,Math,matchMedia:()=>({matches:false}),setTimeout:(fn,ms)=>1,clearTimeout:()=>{}};sb.window=sb;sb.window.scrollTo=()=>{};vm.createContext(sb);vm.runInContext(fs.readFileSync(ROOT+'/content.js','utf8'),sb);vm.runInContext(fs.readFileSync(ROOT+'/app.js','utf8'),sb);return {dev:sb.window.FINPET_DEV,app}}
function assert(v,m){if(!v)throw new Error(m)}
let r=boot(),d=r.dev;
const before=d.getState();d.actions.buyItem('food_basic');let s=d.getState();
assert(s.pet.satiety>before.pet.satiety,'food effect missing');
assert(!s.inventory.some(x=>x.id==='food_basic'),'consumable food incorrectly stored in inventory');
assert(!s.worldPlacements.food_basic,'consumable food incorrectly placed in room');

d.actions.buyItem('interior_lamp');s=d.getState();assert(s.inventory.some(x=>x.id==='interior_lamp')&&s.worldPlacements.interior_lamp?.placed,'durable room item no longer persists');
const src=fs.readFileSync(ROOT+'/app.js','utf8'),css=fs.readFileSync(ROOT+'/styles.css','utf8'),sw=fs.readFileSync(ROOT+'/sw.js','utf8');
assert(src.includes('food_basic:0,food_snack:1,food_treat:2')&&src.includes('shopItemIllustration(item)'),'food illustration mapping missing');
assert(src.includes("data-shop-open=\"Еда\""),'feed action does not open food choices');
assert(!src.includes('Теперь это здесь'),'shop purchase still creates the old item speech bubble');
assert(css.includes('V20 SHOP SEMANTICS'),'shop semantics styles missing');
assert(fs.existsSync(path.join(ROOT,'assets/food-items.webp'))&&fs.statSync(path.join(ROOT,'assets/food-items.webp')).size>10000,'food sprite missing');
assert(sw.includes('./assets/food-items.webp'),'food sprite missing from offline cache');
console.log('shop_presentation_smoke: OK');
