const fs=require('fs');
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
const welcome=fs.readFileSync('welcome.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const req=(ok,msg)=>{if(!ok)throw new Error(msg)};
const motion=app.match(/function motionEnabled\(\)\{([\s\S]*?)\n  \}/)?.[1]||'';
req(motion.includes('return state.settings?.motion!==false;'),'in-app motion toggle is not authoritative');
req(!motion.includes('matchMedia'),'motionEnabled still depends on system reduced-motion');
req(css.includes('html[data-motion="on"] .pet-svg .pet-eyes'),'blink not restored when app motion is on');
req(css.includes('html[data-motion="on"] .screen'),'screen transition not restored when app motion is on');
req(welcome.includes('html[data-motion="on"] .welcome-gate'),'welcome motion override missing');
req(/app\.js\?v=[0-9a-z]+/i.test(index)&&/styles\.css\?v=[0-9a-z]+/i.test(index),'runtime cache-bust missing');
req(/const CACHE = 'finpet-v\d+[^']*';/.test(sw),'service worker cache is not versioned');
console.log('v8_motion_toggle_runtime_smoke: OK');
