const fs=require('fs');
const app=fs.readFileSync('app.js','utf8'),css=fs.readFileSync('styles.css','utf8');
const req=(ok,msg)=>{if(!ok)throw new Error(msg)};
req(app.includes('pet-ear-left')&&app.includes('pet-ear-right'),'pet ears are not independently addressable');
req(app.includes('pet-gaze')&&app.includes('pet-nose')&&app.includes('pet-cheeks'),'pet face micro-motion elements missing');
req(css.includes('@keyframes petEarLeftV9')&&css.includes('@keyframes petGazeV9')&&css.includes('@keyframes petShadowV9'),'V9 pet micro-motion keyframes missing');
req(app.includes('function profileNavIcon()')&&css.includes('.nav-profile-icon .profile-ring'),'round profile nav icon missing');
req(!app.includes('data-difficulty-change'),'difficulty switch must not exist in settings');
req(!app.includes('Режим можно изменить позже в настройках.'),'onboarding still promises settings difficulty switch');
req(app.includes('class="parent-quiz"')&&app.includes("type:'quick_sum'"),'simplified parent check missing');
req(css.includes('html[data-motion="off"] .pet-ear'),'motion off does not stop V9 pet micro-motion');
req(css.includes('html[data-motion="on"] .pet-svg .pet-ear-left'),'explicit V9 motion-on override missing');
req(css.includes('html[data-motion="on"] .pet-svg .pet-gaze'),'explicit V9 gaze motion-on override missing');
console.log('v9_pet_ux_smoke: OK');
