const fs=require('fs');
const read=p=>fs.readFileSync(p,'utf8');
const write=(p,s)=>fs.writeFileSync(p,s);
const must=(s,from,to,label)=>{if(!s.includes(from))throw new Error('Missing '+label);return s.replace(from,to)};

let app=read('app.js');
app=must(app,
"function settingsScreen(){\n    return `<section class=\"screen settings-screen\"><header class=\"settings-header\"><button class=\"linkbtn\" data-back>← Назад</button><h1>Настройки</h1></header><div class=\"settings-group\"><div class=\"section-title\"><h2>Режим игры</h2></div><div class=\"difficulty-settings\"><button class=\"select-card ${state.difficultyMode==='easy'?'active':''}\" data-difficulty-change=\"easy\"><h3>Лёгкий</h3><p>Проще ситуации и больше подсказок.</p></button><button class=\"select-card ${state.difficultyMode==='medium'?'active':''}\" data-difficulty-change=\"medium\"><h3>Средний</h3><p>Больше самостоятельных решений.</p></button></div></div><div class=\"menu settings-list\"><button data-toggle=\"sound\" role=\"switch\" aria-checked=\"${state.settings.sound}\" aria-label=\"Звуки\"><span>Звуки</span><span class=\"setting-control\"><small>${state.settings.sound?'Вкл.':'Выкл.'}</small><span class=\"switch-track\" aria-hidden=\"true\"></span></span></button><button data-toggle=\"motion\" role=\"switch\" aria-checked=\"${state.settings.motion}\" aria-label=\"Анимация\"><span>Анимация</span><span class=\"setting-control\"><small>${state.settings.motion?'Вкл.':'Выкл.'}</small><span class=\"switch-track\" aria-hidden=\"true\"></span></span></button></div><div class=\"settings-reset\"><button class=\"linkbtn danger\" data-reset>Начать заново</button><p class=\"subtle\">Удалить сохранённый прогресс и начать новую игру.</p></div><p class=\"settings-note\">Прогресс сохраняется на этом устройстве.</p>${pageArtwork('settings')}</section>`;\n  }",
"function settingsScreen(){\n    return `<section class=\"screen settings-screen\"><header class=\"settings-header\"><button class=\"linkbtn\" data-back>← Назад</button><h1>Настройки</h1></header><div class=\"settings-group\"><div class=\"section-title\"><h2>Режим игры</h2></div><div class=\"difficulty-settings\"><button class=\"select-card ${state.difficultyMode==='easy'?'active':''}\" data-difficulty-change=\"easy\"><h3>Лёгкий</h3><p>Проще ситуации и больше подсказок.</p></button><button class=\"select-card ${state.difficultyMode==='medium'?'active':''}\" data-difficulty-change=\"medium\"><h3>Средний</h3><p>Больше самостоятельных решений.</p></button></div></div><div class=\"settings-group interface-settings\"><div class=\"section-title\"><h2>Интерфейс</h2></div><div class=\"menu settings-list\"><button data-toggle=\"motion\" role=\"switch\" aria-checked=\"${state.settings.motion!==false}\" aria-label=\"Анимация интерфейса\"><span class=\"setting-copy\"><b>Анимация</b><small>Движения питомца, переходы и реакции на действия</small></span><span class=\"setting-control\"><small>${state.settings.motion!==false?'Вкл.':'Выкл.'}</small><span class=\"switch-track\" aria-hidden=\"true\"></span></span></button><button data-toggle=\"sound\" role=\"switch\" aria-checked=\"${state.settings.sound!==false}\" aria-label=\"Звуки\"><span class=\"setting-copy\"><b>Звуки</b><small>Звуковые реакции приложения</small></span><span class=\"setting-control\"><small>${state.settings.sound!==false?'Вкл.':'Выкл.'}</small><span class=\"switch-track\" aria-hidden=\"true\"></span></span></button></div></div><div class=\"settings-reset\"><button class=\"linkbtn danger\" data-reset>Начать заново</button><p class=\"subtle\">Удалить сохранённый прогресс и начать новую игру.</p></div><p class=\"settings-note\">Прогресс сохраняется на этом устройстве.</p>${pageArtwork('settings')}</section>`;\n  }",
'settingsScreen final');
app=app.replace("if ('serviceWorker' in navigator && location.protocol !== 'file:') navigator.serviceWorker.register('./sw.js').catch(() => {});","if ('serviceWorker' in navigator && location.protocol !== 'file:') navigator.serviceWorker.register('./sw.js', {updateViaCache:'none'}).then(reg=>reg.update()).catch(() => {});");
write('app.js',app);

let styles=read('styles.css');
styles=styles.replace('@keyframes petIdle{0%,100%{transform:translateY(0) rotate(0)}50%{transform:translateY(-3px) rotate(.35deg)}}','@keyframes petIdle{0%,100%{transform:translateY(0) rotate(0)}45%{transform:translateY(-5px) rotate(.55deg)}55%{transform:translateY(-5px) rotate(-.35deg)}}');
styles=styles.replace('.settings-group{margin-bottom:16px}', '.settings-group{margin-bottom:16px}.interface-settings{margin-top:22px}.interface-settings .section-title{margin-bottom:4px}.setting-copy{display:grid;gap:4px;min-width:0}.setting-copy b{font-size:16px;font-weight:600}.setting-copy small{font-size:13px;color:var(--muted);line-height:1.35;max-width:28ch}.interface-settings .settings-list button{gap:16px}.interface-settings .setting-control{flex:0 0 auto}');
write('styles.css',styles);

let sw=read('sw.js');
sw=sw.replace(/const CACHE = '[^']+';/,"const CACHE = 'finpet-v6-motion-runtime-20260917b';");
sw=sw.replace("e.respondWith(caches.match(e.request).then(hit => hit || fetch(e.request).then(r => {\n    const copy = r.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)); return r;\n  }).catch(() => caches.match('./index.html'))));",
"const url=new URL(e.request.url);\n  const core=/\\/(?:index\\.html|styles\\.css|welcome\\.css|content\\.js|app\\.js|welcome\\.js|manifest\\.json)$/.test(url.pathname)||url.pathname.endsWith('/');\n  if(core){\n    e.respondWith(fetch(e.request,{cache:'no-store'}).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r;}).catch(()=>caches.match(e.request).then(hit=>hit||caches.match('./index.html'))));\n    return;\n  }\n  e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r;}).catch(()=>caches.match('./index.html'))));");
write('sw.js',sw);

let index=read('index.html');
index=index.replace('href="styles.css"','href="styles.css?v=20260917b"').replace('href="welcome.css"','href="welcome.css?v=20260917b"').replace('src="content.js"','src="content.js?v=20260917b"').replace('src="app.js"','src="app.js?v=20260917b"').replace('src="welcome.js"','src="welcome.js?v=20260917b"');
write('index.html',index);
console.log('fix_motion_runtime: OK');
